### ISSUE TITLE
Deploy 2 org not working

### ISSUE THREAD

**Issue by Jnew21** [Chaos-Tech-Corp/Input-Field-Lookup#3]
I clicked the deploy 2 org into a sandbox, but I am getting the following error message "Deploying Apex Class [lookupfieldController.apxc] - ... Error (400):
[{"message":"duplicate value found:  duplicates value on record with id: ","errorCode":"DUPLICATE_VALUE","fields":[]}]"

Can you assist as we are trying to use this component ASAP

**Comment by jachaos** [comment]
Hello,

could you check if you already have the component or a class or file with the same name?
I'm still working on deploy2.org to identify existing files and notify the user before hand. The error you see should mean that the apex class already exists. 
Let me know otherwise and I'll check it.
Thanks!

**Comment by jachaos** [comment]
No further comments, I'll close it.
